// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcgswztqwccitfdxnkdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjZ3N3enRxd2NjaXRmZHhua2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTE4NTYsImV4cCI6MjA3Mjg4Nzg1Nn0.TodiCivfTUzxB8mnhsJARaO-1Q0Dl_hrBx6gmISiMEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});